using System.Runtime.CompilerServices;
// <auto-generated>
// This file should only contain assembly level attributes.
// Do not add any class or struct definitions as it may disable the ability of the tool to
// update the file.
// </auto-generated>

using System;

[assembly: InternalsVisibleTo("First Person Shooter.Tests")]
[assembly: InternalsVisibleTo("Assembly-CSharp.Explorables")]

